allow disabling ssl validation
yeraydiazdiaz/sublime-rest-client pull request #29
Opened 2024-03-10 20:27 UTC by maddanio

this adds an option to disable ssl cerrtificate validation.

we really need this in our case as we have some internal servers in an isolated vpn where we use self-signed certificates.

an alternative would be to allow additional certificates. but that is likely trickier and I would like to use this for now.

not sure if this is the right way. I could not find the settings in the settings menu, also not sure if sublime will actually apply this directly. didnt seem so. help welcome :)

2024-03-12 22:17 UTC, yeraydiazdiaz requested changes
Thanks! This looks good, just a couple of comments.

2024-03-12 22:17 UTC, yeraydiazdiaz commented on REST.sublime-settings
> +    "disable_ssl_validation": true,
This should default to `false`

2024-03-12 22:17 UTC, yeraydiazdiaz commented on plugin.py
> +client.setup(settings)
I'm not sure loading the settings at the module importing phase is a good practise in ST.

Could we keep the loading of settings in the command and call `setup` from there?

2024-03-13 19:04 UTC, maddanio commented on plugin.py
> +client.setup(settings)
I dont really know how settings changes propagate. That could be done, but the maybe better to just have 2 connection pools, so we don't have to worry about concurrency?

2024-03-13 20:28 UTC, maddanio commented on plugin.py
> +client.setup(settings)
Actually it should be ok to exchange it when needed, hmm, with a lock...let me see

2024-03-16 17:01 UTC, yeraydiazdiaz commented on plugin.py
> +client.setup(settings)
I did a quick test and it seems ST4 reloads the settings when there's a change, but I think if we instantiate the pool in __init__ or at module import, it'll _probably_ not pick up the changes.

However, there's an [add_on_change](https://www.sublimetext.com/docs/api_reference.html#sublime.Settings) callback we could try using to recreate the pool, we could try using that.

2024-03-17 09:14 UTC, maddanio commented on REST.sublime-settings
> +    "disable_ssl_validation": true,
Totally:)

2024-03-17 09:15 UTC, maddanio commented on plugin.py
> +client.setup(settings)
Ah yes, i think that is best. And the access to the pool should be locked then, since the actual request is in a thread

2024-03-22 20:02 UTC, maddanio commented on REST.sublime-settings
> +    "disable_ssl_validation": true,
done

2024-03-22 20:03 UTC, maddanio commented on plugin.py
> +client.setup(settings)
ok, not sure if its pretty, but it does what it should now, i.e. react properly ro settings changes

2024-04-11 13:24 UTC, maddanio commented
@yeraydiazdiaz care to have a look again?

2024-04-23 21:48 UTC, yeraydiazdiaz commented
Hi @maddanio, thanks for your work on this. I've been looking at VSCode's REST client and I think [their approach regarding SSL certificates](https://github.com/Huachao/vscode-restclient?tab=readme-ov-file#ssl-client-certificates) is better in the sense that it's probably worth not allowing disabling SSL validation globally but for specific hosts. This is something that sounds like a good idea anyway moving forward as it's very likely users would want separate configuration (e.g. timeouts, proxies, etc) per target host.

This changes the code quite a bit because we'd need different connection pools per host. I've been working on it and have a working solution, I just need to do some cleanup.

With that in mind I think I'll close this PR, thanks again! 👍🏻

2024-04-23 21:48 UTC, closed without merging

2024-04-24 05:59 UTC, maddanio commented
ok, looking forward to that. what I have been wondering is, wether there may be a way to shortcut requests somehow, having to openb them as documents is annoying, as you have to either keep on navigating there or hope they are still in the recents

2024-05-02 22:05 UTC, yeraydiazdiaz commented
Hi @maddanio, I'm releasing version 1.1.0 now with the SSL validation option, hopefully it'll cover your use case as expected.

> hat I have been wondering is, wether there may be a way to shortcut requests somehow, having to openb them as documents is annoying, as you have to either keep on navigating there or hope they are still in the recents

I don't think that's something REST Client should do as it falls under management of buffers in Sublime Text. What I tend to do is save the response as files so I can refer to them later on. There may be other extensions that can help, but I'd like to keep REST Client quite focused on HTTP requests.

2024-05-03 08:26 UTC, maddanio commented
yes I also figured that. it's bascially a bookmarking menu or so that would make sense, but thats definitely a separate extension. thanks a lot!

2024-05-03 08:29 UTC, maddanio commented
the only thing: a host pattern would be useful for us. or even a per-request setting. as we have 40 hosts we need this for (our own server pool).